version: '3.8'
services:
  nginx:
    container_name: nginx15
    image: nginx:stable-alpine
    restart: unless-stopped
    build: ./docker/nginx
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: laravel-filament/php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "internal.host:host-gateway"
    networks:
      - lf
    depends_on:
      - nginx

  mysql:
    container_name: mysql8
    platform: linux/amd64
    image: mysql:8.0.39
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3396:3306"
    networks:
      - lf

networks:
  lf:
    driver: bridge
